version: "3"

services:
  rentacar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - rentacarapi

    
  rentacar-api:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:RentacarConnection=Server=rentacar-sql,1433;Database=CarRental;User=sa;Password=QWElkj132!;ConnectRetryCount=30
    ports:
      - 5000:80
    networks:
      - rentacarapi
    links:
      - rentacar-sql
    depends_on:
      - rentacar-sql

networks:
  rentacarapi:
    driver: bridge